home/urls.py
from django.conf.urls import url

from home import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

p2pcourier/urls.py
from django.conf.urls import include, url, patterns, static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from envelope.views import ContactView
from home.shared import anonymous_required
from home.sitemaps import HomeStaticViewSitemap
from overrides.forms import MyRegistrationForm
from pages.sitemaps import PagesStaticViewSitemap
from registration.backends.default.views import RegistrationView
from search.views import TravelsSearchView, ParcelsSearchView
from travels.sitemaps import TravelSitemap
from parcels.sitemaps import ParcelSitemap

sitemaps = {
    'home': HomeStaticViewSitemap,
    'static': PagesStaticViewSitemap,
    'requests': ParcelSitemap,
    'travels': TravelSitemap,
}

urlpatterns = [
    url(r'^', include('home.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', anonymous_required(
        RegistrationView.as_view(form_class=MyRegistrationForm)),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^contact/', ContactView.as_view(success_url="/pages/thankyou"),
        name='envelope-contact'),
    url(r'^messages/', include('django_messages.urls', namespace='messages')),
    url(r'^pages/', include('pages.urls')),
    url(r'^travels/', include('travels.urls')),
    url(r'^requests/', include('parcels.urls')),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^search-travels/', TravelsSearchView(), name='search-travels'),
    url(r'^search-requests/', ParcelsSearchView(), name='search-requests'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

parcels/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required as log
from parcels import views

urlpatterns = [
    url(r'^$', views.ParcelList.as_view(), name="parcels"),
    url(r'^(?P<pk>\d+)(?:/(?P<slug>[\w\d-]+))?/$',
        log(views.ParcelDetail.as_view()), name="parcel-detail"),
    url(r'^new$', log(views.ParcelCreate.as_view()), 
        name="parcel-new"),
    url(r'^update/(?P<pk>\d+)(?:/(?P<slug>[\w\d-]+))?/$',
        log(views.ParcelUpdate.as_view()), name="parcel-update"),
    url(r'^delete/(?P<pk>\d+)(?:/(?P<slug>[\w\d-]+))?/$',
        log(views.ParcelDelete.as_view()), name="parcel-delete"),
]

parcels/models.py
from django.db import models
from home.models import BaseModel
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from autoslug import AutoSlugField


@python_2_unicode_compatible
class Parcel(BaseModel):
    """
    This model contains all the parcels
    """
    requester = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,)
    origin = models.ForeignKey('cities_light.City', null=True,
                               related_name='origin_parcel')
    destination = models.ForeignKey('cities_light.City', null=True,
                                    related_name='destination_parcel')
    delivery_date = models.DateField(_("Delivery date"),)
    notes = models.TextField(_("Details"), blank=True)
    slug = AutoSlugField(populate_from='get_slug_name', always_update=True)

    # Size choices
    SIZES = (
        ('small', _('Small (roughly A5-paper size parcel)')),
        ('medium', _('Medium (roughly A4-paper size parcel)')),
        ('large', _('Large (parcel bigger than A4-paper size)')),
        (None, _('Please pick a size')),
    )

    # Weight choices, should be localised depending on locale
    WEIGHTS = (
        ('light', _('Light (up to 0.5 kg)')),
        ('medium', _('Medium (up to 1 kg)')),
        ('heavy', _('Heavy (more than 1 kg)')),
        (None, _('Please pick a weight')),
    )


    size = models.CharField(max_length=10, choices=SIZES)

    weight = models.CharField(max_length=10, choices=WEIGHTS)

    flexible = models.BooleanField(_("Date flexible"), default=False)

    tips = models.BooleanField(_("Tips"), default=False)

    def past_request(self):
        now = timezone.now().date()
        return self.delivery_date < now

    def __str__(self):
        if self.requester.first_name:
            name = self.requester.first_name
        else:
            name = self.requester.username
        pattern = _(u"{} has a parcel for delivery from {}, {} to {}, {} by {}")
        return pattern.format(
            name, self.origin.name_ascii, self.origin.country.name_ascii,
            self.destination.name_ascii, self.destination.country.name_ascii,
            self.delivery_date.strftime('%d %B %Y'))


    def get_absolute_url(self):
        """
        Gets the url of the object to its detail view page
        """
        return reverse('parcel-detail', args=(str(self.id), self.slug))

    def get_slug_name(self):
        """
        Return a slug name for this model
        """
        return "{}-{}".format(self.origin.name_ascii.lower(),
            self.destination.name_ascii.lower())

    class Meta:
        verbose_name = _('request')
        verbose_name_plural = _('requests')

parcels/forms.py
import autocomplete_light.shortcuts as autocomplete_light

from django.forms import ModelForm, TextInput, Select, CheckboxInput, Textarea
from django import forms
from django.utils.translation import ugettext_lazy as _
from parcels.models import Parcel
from home.forms import HomeForm



class ParcelForm(autocomplete_light.ModelForm):

    class Meta:
        def merge_dicts(x, y):
            """
            Given two dicts, merge them and return
            """
            z = x.copy()
            z.update(y)
            return z

        model = Parcel

        fields = (
            'origin',
            'destination',
            'delivery_date',
            'flexible',
            'tips',
            'size',
            'weight',
            'notes',
        )


        labels = {
            'origin': 'Originating city',
        }


        help_texts = {
            'origin': _('Where the parcel needs to be collected from'),
            'destination': _('Where the parcel needs to be delivered to'),
            'delivery_date': _('Needs to be delivered by this date'),
            'flexible': _('If your delivery date is flexible'),
            'tips': _('If you are happy to tip'),
            'size': _('Approximate size'),
            'weight': _('Approximate weight'),
            'notes': _('The more details you provide the more chances you '
                      'will be contacted by travellers'),
        }

        # Custom widget attrs
        autocomplete_attrs = {
            'data-autocomplete-minimum-characters': 3,
            'placeholder': _('e.g. London'),
            'class': 'input rounded',
        }


        autocomplete_widget_attrs = {
            'style': 'display:block;',
        }


        datepicker_attrs = {
            'class': 'rounded',
            'placeholder': _('Pick a date'),
        }


        bootstrap_attrs = {'class': 'rounded'}


        widgets = {
            'origin': autocomplete_light.ChoiceWidget('CityAutocomplete',
                attrs=merge_dicts(autocomplete_attrs,
                                  {'autofocus': ''}),
                widget_attrs=autocomplete_widget_attrs),

            'destination': autocomplete_light.ChoiceWidget('CityAutocomplete',
                attrs=merge_dicts(autocomplete_attrs,
                                  {'placeholder': _('e.g. New York')}),
                widget_attrs=autocomplete_widget_attrs),

            'delivery_date': TextInput(attrs=merge_dicts(datepicker_attrs,
                {'required': True})),

            'size': Select(attrs=merge_dicts(bootstrap_attrs,
                {'required': True})),

            'weight': Select(attrs=merge_dicts(bootstrap_attrs,
                {'required': True})),

            'flexible': CheckboxInput(attrs=bootstrap_attrs),

            'tips': CheckboxInput(attrs=bootstrap_attrs),

            'notes': Textarea(attrs=bootstrap_attrs),
        }


class ParcelListForm(HomeForm):

    date = forms.DateField(widget=forms.DateInput(attrs={
            'class': 'form-control',
            'placeholder': _('Delivery date'),
        }
    ), required=False)

    class Meta:
        fields = (
            'fr',
            'to',
            'date',
        )

parcels/views.py
from django.views import generic
from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import Http404
from parcels.models import Parcel
from parcels.forms import ParcelForm, ParcelListForm
from django_messages.forms import ComposeForm
from parcels.tasks import inform_travellers_task
from django.views.generic.edit import FormView
from django.utils.translation import ugettext as _


class ParcelList(generic.ListView, FormView):
    """
    List view of all available requests
    """
    template_name = 'parcels/parcel_list.html'
    queryset = Parcel.objects.all().order_by('-delivery_date')
    form_class = ParcelListForm

class ParcelDetail(generic.DetailView):
    """
    Parcel detail view for a single post and apply
    TODO: Currently recipient and subject are just hidden, we need to modify
    forms to ignore changes coming from post and use details we want, i.e.
    someone can "unhide" recipient and subject and send whatever they want
    """
    template_name = 'parcels/parcel_detail.html'
    model = Parcel
    queryset = Parcel.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ParcelDetail, self).get_context_data(**kwargs)
        parcel = self.get_object()
        context['form'] = ComposeForm()
        context['subject'] = \
            _('Request to deliver a package from {} to {}').format(
                parcel.origin.name_ascii, parcel.destination.name_ascii)
        context['message_placeholder'] = \
            _('Please describe your travel details here.')
        return context


class ParcelCreate(generic.CreateView):
    """
    Parcel create view
    """
    template_name = 'parcels/parcel_form.html'
    model = Parcel
    form_class = ParcelForm

    def form_valid(self, form):
        form.instance.requester = self.request.user
        return super(ParcelCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, _('Request successfully created'))
        inform_travellers_task.delay(self.object.id)
        return reverse('parcel-detail',
                       args=(self.object.id, self.object.slug))


class ParcelUpdate(generic.UpdateView):
    """
    Parcel update view
    """
    template_name = 'parcels/parcel_form.html'
    model = Parcel
    form_class = ParcelForm

    def get_success_url(self):
        messages.success(self.request, _('Request successfully updated'))
        inform_travellers_task.delay(self.object.id)
        return reverse('parcel-detail',
                       args=(self.object.id, self.object.slug))


class ParcelDelete(generic.DeleteView):
    """
    Parcel delete view
    """
    model = Parcel

    def get_success_url(self):
        messages.success(self.request, _('Request successfully deleted'))
        return reverse_lazy('parcels')

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user """
        parcel_to_delete = super(ParcelDelete, self).get_object()
        if not parcel_to_delete.requester == self.request.user:
            raise Http404
        return parcel_to_delete

parcels/templates/parcels/parcel_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load tz %}
{% load i18n %}
{% block title %}
<title>{% trans 'Request' %} | Post4Tips</title>
{% endblock %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'assets/plugins/sky-forms-pro/skyforms/css/sky-forms.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/sky-forms-pro/skyforms/custom/custom-sky-forms.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker3.css' %}">
{% endblock %}
{% block content %}
<div class="container content">
    <header class="headline">
      <h2>{% trans 'Request Details' %}</h2>
    </header>
  <div class="row">
    <section class="col-md-5 col-xs-12 bq-green">
        <h4><em>{% trans 'From' %}</em></h4>
        <p class="lead">{{ parcel.origin.get_display_name }}</p>
    </section>
    <section class="col-md-2 col-xs-12 service-block">
      <i class="icon-custom icon-custom-detail icon-color-u icon-lg rounded-x icon-line icon-travel-064" data-toggle="tooltip" data-original-title="{% trans 'Here you are - help yourself with a cup of tea :)' %}"></i>
    </section>
    <section class="col-md-5 col-xs-12 text-right bq-green">
        <h4><em>{% trans 'To' %}</em></h4>
        <p class="lead">{{ parcel.destination.get_display_name }}</p>
    </section>
  </div>
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <dl class="col-md-6 content-boxes-v3">
        <div class="clearfix margin-bottom-15">
          <a href="{% url 'account-guest-view' parcel.requester.id %}"><i class="icon-custom icon-custom-detail icon-color-u icon-lg rounded-x icon-line icon-travel-018" data-toggle="tooltip" data-original-title="{% trans 'View user account' %}"></i></a>
          <div class="content-boxes-in-v3">
            <h5 class="content-h5-margin"><em><strong>{% trans 'Requester' %}</strong></em></h5>
            <h4>{% if parcel.requester.first_name or parcel.requester.last_name %}
                  {{ parcel.requester.get_full_name }}
                {% else %}
                  {{ parcel.requester.username }}
                {% endif %}
            </h4>
          </div>
        </div>
      </dl>
      <dl class="col-md-6 content-boxes-v3">
        <div class="clearfix margin-bottom-15">
          <i class="icon-custom icon-custom-detail icon-color-u icon-lg rounded-x icon-line icon-communication-146"></i>
          <div class="content-boxes-in-v3">
            <h5 class="content-h5-margin"><em><strong>{% trans 'Date to be delivered by' %}</strong></em></h5>
            <h4>{{ parcel.delivery_date|date:"d E Y" }}</h4>
          </div>
        </div>
      </dl>
      <div class="headline">
        <h4>{% trans 'Additional details' %}</h4>
      </div>
      <dl>
        <dt>{% trans 'Weight' %}</dt>
        <dd>{{ parcel.get_weight_display }}</dd>
        <dt>{% trans 'Size' %}</dt>
        <dd>{{ parcel.get_size_display }}</dd>
        <dt>{% trans 'Delivery date flexible' %}</dt>
        <dd>{% if parcel.flexible %}{% trans 'Yes' %}{% else %}No{% endif %}</dd>
        <dt>{% trans 'Requester happy to tip' %}</dt>
        <dd>{% if parcel.tips %}{% trans 'Yes' %}{% else %}No{% endif %}</dd>
        {% if parcel.notes %}
        <dt>{% trans 'More details' %}</dt>
        <dd>{{ parcel.notes }}</dd>
        {% endif %}
      </dl>
    </div>
    <div class="col-md-6 col-xs-12">
      <input type="hidden" id="origin-latitude" name="variable" value="{{ parcel.origin.latitude }}" readonly>
      <input type="hidden" id="origin-longitude" name="variable" value="{{ parcel.origin.longitude }}" readonly>
      <input type="hidden" id="destination-latitude" name="variable" value="{{ parcel.destination.latitude }}" readonly>
      <input type="hidden" id="destination-longitude" name="variable" value="{{ parcel.destination.longitude }}" readonly>
      <div id="map" class="map margin-bottom-50"></div>
    </div>
  </div>
  {% if user == parcel.requester %}
    <form action="{% url 'parcel-delete' parcel.id parcel.slug %}" method="post" class="form-horizontal">
      {% csrf_token %}
      <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">{% trans 'Back' %}</button>
      <a class="btn-u btn-u-default" href="{% url 'parcel-update' parcel.id parcel.slug %}">{% trans 'Edit' %}</a>
      <button onclick="return confirm('Are you sure you want to delete this request?')" class="btn-u btn-u-red">{% trans 'Delete' %}</button>
    </form>
  {% else %}
  <a class="btn-u btn-u-default" href="javascript:history.back()">{% trans 'Back' %}</a>
  <!-- Bootstrap Modals With Forms -->
    <button class="btn-u" data-toggle="modal" data-target="#responsive">{% trans 'Apply' %}</button>
    <div class="modal fade" id="responsive" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="{% url 'messages:messages_compose' %}?next={% url 'parcel-detail' parcel.id %}" class="sky-form form-horizontal" method="post">
                {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel4">{{ subject }}</h4>
                </div>
                <div class="modal-body">
                    <input id="{{ form.recipient.id_for_label }}" name="{{ form.recipient.html_name }}" type="hidden" value="{{ parcel.requester.username }}">
                    <input id="{{ form.subject.id_for_label }}" name="{{ form.subject.html_name }}" type="hidden" value="{{ subject }}">
                    <div class="row">
                        <div class="col-md-12 col-xs-10">
                            <label class="textarea textarea-resizable {% if form.body.errors %} state-error{% endif %}">
                                <textarea style="height: 150px;" id="{{ form.body.id_for_label }}" name="{{ form.body.html_name }}" placeholder="{{ message_placeholder }}" autofocus></textarea>
                            </label>
                            {% if form.body.help_text %}
                            <span id="help_{{ form.body.html_name }}" class="help-block">{{ form.body.help_text }}</span>
                            {% endif %}
                            {% if form.body.errors %}
                            {% for error in form.body.errors %}
                            <div class="alert alert-danger" role="alert">
                              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                              <span class="sr-only">{% trans 'Error:' %}</span>
                                {{ error|escape }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-u btn-u-default" data-dismiss="modal">{% trans 'Close' %}</button>
                    <button type="submit" id="submit" class="btn-u btn-u-primary odom-submit">{% trans 'Send' %}</button>
                </div>
                </form>
            </div>
        </div>
    </div>
<!-- End Bootstrap Modals With Forms -->
  {% endif %}
</div>
{% endblock %}
{% block foot %}
{{ block.super }}
<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyAia8-jJOAo2XJL7Tk3QedcbpV11OWR9Ls"></script>
<script type="text/javascript" src="{% static 'assets/plugins/gmap/gmap.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/maps.js' %}"></script>
{% endblock %}

parcels/templates/parcels/parcel_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load tz %}
{% load i18n %}
{% block title %}
<title>{% trans 'Request' %} | Post4Tips</title>
{% endblock %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'assets/plugins/font-awesome/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/sky-forms-pro/skyforms/css/sky-forms.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/sky-forms-pro/skyforms/custom/custom-sky-forms.css' %}">
{% endblock %}
{% block content %}
<div class="container content">
    <form id="skyform" enctype="multipart/form-data" method="post" class="sky-form form-horizontal">
      {% csrf_token %}
      <header>
      {% if parcel %}
        <h2>{% trans 'Update Request' %}</h2>
        <h4>{% trans 'Update the request by modifying fields below' %}</h4>
      {% else %}
        <h2>{% trans 'New Request' %}</h2>
        <h4>{% trans 'Create a new request by filling out the form below' %}</h4>
      {% endif %}
      </header>
      <fieldset>
        <div class="row">
        <!-- Origin -->
          <section class="col-md-5 col-xs-10">
            <label class="label" for="{{ form.origin.id_for_label }}">{{ form.origin.label }}</label>
            <label class="input{% if form.origin.errors %} state-error{% endif %}">{{ form.origin }}</label>
            {% if form.origin.help_text %}
            <span id="help_{{ form.origin.html_name }}" class="help-block">{{ form.origin.help_text }}</span>
            {% endif %}
            {% if form.origin.errors %}
            {% for error in form.origin.errors %}
            <div class="alert alert-danger" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <span class="sr-only">{% trans 'Error:' %}</span>
                {{ error|escape }}
            </div>
            {% endfor %}
            {% endif %}
          </section>
        <!-- End Origin -->
        <!-- Icon -->
          <section class="col-md-2 col-xs-2 service-block">
            <i class="icon-custom icon-custom-forms icon-color-u icon-lg rounded-x icon-line icon-directions"></i>
          </section>
        <!-- Destination -->
          <section class="col-md-5 col-xs-10">
            <label class="label" for="{{ form.destination.id_for_label }}">{{ form.destination.label }}</label>
            <label class="input{% if form.destination.errors %} state-error{% endif %}">{{ form.destination }}</label>
            {% if form.destination.help_text %}
            <span id="help_{{ form.destination.html_name }}" class="help-block">{{ form.destination.help_text }}</span>
            {% endif %}
            {% if form.destination.errors %}
            {% for error in form.destination.errors %}
            <div class="alert alert-danger" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <span class="sr-only">{% trans 'Error:' %}</span>
                {{ error|escape }}
            </div>
            {% endfor %}
            {% endif %}
          </section>
        </div>
        <!-- Delivery date -->
        <div class="row">
          <section class="col-md-5 col-xs-10">
            <label class="label" for="{{ form.delivery_date.id_for_label }}">{{ form.delivery_date.label }}</label>
            <label class="input{% if form.delivery_date.errors %} state-error{% endif %}">{{ form.delivery_date }}</label>
            {% if form.delivery_date.help_text %}
            <span id="help_{{ form.delivery_date.html_name }}" class="help-block">{{ form.delivery_date.help_text }}</span>
            {% endif %}
            {% if form.delivery_date.errors %}
            {% for error in form.delivery_date.errors %}
            <div class="alert alert-danger" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <span class="sr-only">{% trans 'Error:' %}</span>
                {{ error|escape }}
            </div>
            {% endfor %}
            {% endif %}
          </section>
        <!-- Icon -->
          <section class="col-md-2 col-xs-2 service-block">
            <i class="icon-custom icon-custom-forms icon-color-u icon-lg rounded-x icon-line icon-calendar"></i>
          </section>
        </div>
      </fieldset>
      <fieldset>
        <div class="row">
          <!-- Size -->
          <section class="col-md-5 col-xs-10">
            <label class="label" for="{{ form.size.id_for_label }}">{{ form.size.label }}</label>
            <label class="select{% if form.size.errors %} state-error{% endif %}">{{ form.size }}<i></i></label>
            {% if form.size.help_text %}
            <span id="help_{{ form.size.html_name }}" class="help-block">{{ form.size.help_text }}</span>
            {% endif %}
            {% if form.size.errors %}
            {% for error in form.size.errors %}
            <div class="alert alert-danger" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <span class="sr-only">{% trans 'Error:' %}</span>
                {{ error|escape }}
            </div>
            {% endfor %}
            {% endif %}
          </section>
          <!-- Icon -->
          <section class="col-md-2 col-xs-2 service-block">
            <i class="icon-custom icon-custom-forms icon-color-u icon-lg rounded-x icon-line icon-travel-089"></i>
          </section>
          <!-- Weight -->
          <section class="col-md-5 col-xs-10">
            <label class="label" for="{{ form.weight.id_for_label }}">{{ form.weight.label }}</label>
            <label class="select{% if form.weight.errors %} state-error{% endif %}">{{ form.weight }}<i></i></label>
            {% if form.weight.help_text %}
            <span id="help_{{ form.weight.html_name }}" class="help-block">{{ form.weight.help_text }}</span>
            {% endif %}
            {% if form.weight.errors %}
            {% for error in form.weight.errors %}
            <div class="alert alert-danger" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <span class="sr-only">{% trans 'Error:' %}</span>
                {{ error|escape }}
            </div>
            {% endfor %}
            {% endif %}
          </section>
        </div>
      </fieldset>
      <fieldset>
        <div class="row">
            <!-- Notes -->
          <section class="col-md-5 col-xs-10">
            <label class="label" for="{{ form.notes.id_for_label }}">{{ form.notes.label }}</label>
            <label class="textarea">{{ form.notes }}<i></i></label>
            {% if form.notes.help_text %}
            <span id="help_{{ form.notes.html_name }}" class="help-block">{{ form.notes.help_text }}</span>
            {% endif %}
            {% if form.notes.errors %}
            {% for error in form.notes.errors %}
            <div class="alert alert-danger" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <span class="sr-only">{% trans 'Error:' %}</span>
                {{ error|escape }}
            </div>
            {% endfor %}
            {% endif %}
          </section>
      </fieldset>
      <fieldset>
        <div class="row">
            <!-- Flexible -->
          <section class="col-md-5 col-xs-10">
            {# <!-- This styling here nicely aligns label with the checkbox --> #}
            <label style="overflow: hidden; padding: 0px 0px 0px 25px;" class="checkbox">{{ form.flexible }}<i></i>{{ form.flexible.label }}</label>
            {% if form.flexible.help_text %}
            <span id="help_{{ form.flexible.html_name }}" class="help-block">{{ form.flexible.help_text }}</span>
            {% endif %}
            {% if form.flexible.errors %}
            {% for error in form.flexible.errors %}
            <div class="alert alert-danger" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <span class="sr-only">{% trans 'Error:' %}</span>
                {{ error|escape }}
            </div>
            {% endfor %}
            {% endif %}
          </section>

          <section class="col-md-5 col-xs-10">
            <label style="overflow: hidden; padding: 0px 0px 0px 25px;" class="checkbox">{{ form.tips }}<i></i>{{ form.tips.label }}</label>
            {% if form.tips.help_text %}
            <span id="help_{{ form.tips.html_name }}" class="help-block">{{ form.tips.help_text }}</span>
            {% endif %}
            {% if form.tips.errors %}
            {% for error in form.tips.errors %}
            <div class="alert alert-danger" role="alert">
              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
              <span class="sr-only">{% trans 'Error:' %}</span>
                {{ error|escape }}
            </div>
            {% endfor %}
            {% endif %}
          </section>
        </div>
      </fieldset>
      <footer>
        <button type="submit" class="btn-u">{% trans 'Submit' %}</button>
        <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">{% trans 'Back' %}</button>
      </footer>
    </form>
</div>
{% endblock %}
{% block foot %}
{{ block.super }}
<script type="text/javascript" src="{% static 'assets/js/plugins/datepicker.js' %}"></script>
<script type="text/javascript">
    jQuery(document).ready(function() {
        App.init();
        Datepicker.initDatepicker();
    });
</script>
<link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
{% endblock %}