home/urls.py
from django.conf.urls import url

from home import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

p2pcourier/urls.py
from django.conf.urls import include, url, patterns, static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from envelope.views import ContactView
from home.shared import anonymous_required
from home.sitemaps import HomeStaticViewSitemap
from overrides.forms import MyRegistrationForm
from pages.sitemaps import PagesStaticViewSitemap
from registration.backends.default.views import RegistrationView
from search.views import TravelsSearchView, ParcelsSearchView
from travels.sitemaps import TravelSitemap
from parcels.sitemaps import ParcelSitemap

sitemaps = {
    'home': HomeStaticViewSitemap,
    'static': PagesStaticViewSitemap,
    'requests': ParcelSitemap,
    'travels': TravelSitemap,
}

urlpatterns = [
    url(r'^', include('home.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', anonymous_required(
        RegistrationView.as_view(form_class=MyRegistrationForm)),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^contact/', ContactView.as_view(success_url="/pages/thankyou"),
        name='envelope-contact'),
    url(r'^messages/', include('django_messages.urls', namespace='messages')),
    url(r'^pages/', include('pages.urls')),
    url(r'^travels/', include('travels.urls')),
    url(r'^requests/', include('parcels.urls')),
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^search-travels/', TravelsSearchView(), name='search-travels'),
    url(r'^search-requests/', ParcelsSearchView(), name='search-requests'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

travels/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from travels import views

urlpatterns = [
    url(r'^$', views.TravelList.as_view(), name='travels'),
    url(r'^(?P<from>\w+)(?P<to>\w+)(?P<date>\d{4}-\d{2}-\d{2})$',
        views.TravelList.as_view(), name='travels-search'),
    url(r'^(?P<pk>\d+)(?:/(?P<slug>[\w\d-]+))?/$',
        login_required(views.TravelDetail.as_view()), name='travel-detail'),
    url(r'^new$', login_required(views.TravelCreate.as_view()),
        name='travel-new'),
    url(r'^edit/(?P<pk>\d+)(?:/(?P<slug>[\w\d-]+))?/$',
        login_required(views.TravelUpdate.as_view()), name='travel-edit'),
    url(r'^delete/(?P<pk>\d+)(?:/(?P<slug>[\w\d-]+))?/$',
        login_required(views.TravelDelete.as_view()), name='travel-delete'),
]

travels/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from autoslug import AutoSlugField
from home.models import BaseModel


@python_2_unicode_compatible
class Travel(BaseModel):
    """
    Model describing the present and past travels
    """
    traveller = models.ForeignKey(settings.AUTH_USER_MODEL,
        verbose_name=_('traveller'), on_delete=models.CASCADE)
    origin = models.ForeignKey('cities_light.City', null=True,
        verbose_name=_('origin'), related_name='origin')
    destination = models.ForeignKey('cities_light.City', null=True,
        verbose_name=_('destination'), related_name='destination')
    journey_start = models.DateField(_("Journey start date"))
    journey_end = models.DateField(_("Journey end date"), blank=True)
    over = models.BooleanField(_("Travel is over?"), default=False)
    recurring = models.BooleanField(_("Recurring travel"), default=False)
    free = models.BooleanField(_("Can carry for free"), default=False)
    slug = AutoSlugField(populate_from='get_slug_name', always_update=True)

    # Size choices
    SIZES = (
        ('small', _('Small (roughly A5-paper size parcel)')),
        ('medium', _('Medium (roughly A4-paper size parcel)')),
        ('large', _('Large (bigger parcel)')),
        (None, _('Please pick a size')),
    )

    # Weight choices, should be localised depending on locale
    WEIGHTS = (
        ('light', _('Light (up to 0.5 kg)')),
        ('medium', _('Medium (up to 1 kg)')),
        ('heavy', _('Heavy (more than 1 kg)')),
        (None, _('Please pick a weight')),
    )

    # Travel type
    TYPES = (
        ('road', _('Road')),
        ('sea', _('Sea')),
        ('air', _('Air')),
        ('train', _('Rail')),
        ('walk', _('Walk')),
        ('interstellar', _('Interstellar')),
        (None, _('Optionally pick a journey type')),
    )

    max_size = models.CharField(max_length=10, choices=SIZES)
    max_weight = models.CharField(max_length=10, choices=WEIGHTS)
    journey_type = models.CharField(max_length=15, choices=TYPES, blank=True,
                                    default=None)

    def __str__(self):
        if self.traveller.first_name:
            name = self.traveller.first_name
        else:
            name = self.traveller.username
        return _(u"{} travels from {}, {} to {}, {} on {}").format(
            name, self.origin.name_ascii, self.origin.country.name_ascii,
            self.destination.name_ascii, self.destination.country.name_ascii,
            self.journey_start.strftime('%d %B %Y'))

    def past_travel(self):
        now = timezone.now().date()
        return self.journey_start < now

    past_travel.admin_order_field = 'journey_start'
    past_travel.boolean = True
    past_travel.short_description = _('Past travel?')

    def clean(self):
        if not self.journey_end:
            self.journey_end = self.journey_start
        # journey_end should not be before journey_start
        if self.journey_end < self.journey_start:
            raise ValidationError({
                'journey_end': _('Journey end time can not be before '
                                  'start time!')
            })

    def get_absolute_url(self):
        """
        Handy way of getting the url of the object to its detail view page
        """
        return reverse('travel-detail', args=(str(self.id), self.slug))

    def get_slug_name(self):
        """
        Return a slug name for this model
        """
        return "{}-{}".format(self.origin.name_ascii.lower(),
            self.destination.name_ascii.lower())

    class Meta:
        verbose_name = _('travel')
        verbose_name_plural = _('travels')

travels/forms.py
import autocomplete_light.shortcuts as autocomplete_light

from django.forms import ModelForm, TextInput, Select, CheckboxInput
from django import forms
from django.utils.translation import ugettext_lazy as _
from travels.models import Travel
from home.forms import HomeForm


class TravelForm(autocomplete_light.ModelForm):

    class Meta:
        def merge_dicts(x, y):
            """
            Given two dicts, merge them and return
            """
            z = x.copy()
            z.update(y)
            return z

        model = Travel

        fields = (
            'origin',
            'destination',
            'journey_start',
            'journey_end',
            'journey_type',
            'max_size',
            'max_weight',
            'free',
            'over',
        )
        labels = {
            'origin': _('From'),
            'destination': _('To'),
        }
        help_texts = {
            'origin': _('Start typing the name of the city you are travelling'
                       ' from'),
            'destination': _('Start typing the name of the city you are travel'
                            'ling to'),
            'journey_start': _('Date when you intend to travel'),
            'journey_end': _('Optionally include end date'),
        }
        # Custom widget attrs
        autocomplete_attrs = {
            'data-autocomplete-minimum-characters': 3,
            'placeholder': _('e.g. London'),
            'class': 'input rounded',
        }
        autocomplete_widget_attrs = {
            'style': 'display:block;',
        }
        datepicker_attrs = {
            'placeholder': _('Pick a date'),
            'class': 'rounded',
        }
        bootstrap_attrs = {'class': 'rounded'}
        widgets = {
            'origin': autocomplete_light.ChoiceWidget('CityAutocomplete',
                attrs=merge_dicts(autocomplete_attrs,
                                  {'autofocus': ''}),
                widget_attrs=autocomplete_widget_attrs),
            'destination': autocomplete_light.ChoiceWidget('CityAutocomplete',
                attrs=merge_dicts(autocomplete_attrs,
                                  {'placeholder': _('e.g. New York')}),
                widget_attrs=autocomplete_widget_attrs),
            'journey_start': TextInput(attrs=merge_dicts(datepicker_attrs,
                {'required': True})),
            'journey_end': TextInput(attrs=datepicker_attrs),
            'max_size': Select(attrs=merge_dicts(bootstrap_attrs,
                {'required': True})),
            'max_weight': Select(attrs=merge_dicts(bootstrap_attrs,
                {'required': True})),
            'journey_type': Select(attrs=bootstrap_attrs),
            'free': CheckboxInput(attrs=bootstrap_attrs),
            'over': CheckboxInput(attrs=bootstrap_attrs),
        }


class TravelListForm(HomeForm):

    date = forms.DateField(widget=forms.DateInput(attrs={
            'class': 'form-control',
            'placeholder': _('Jorney start date'),
        }
    ), required=False)

    class Meta:
        fields = (
            'fr',
            'to',
            'date',
        )

travels/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import Http404
from django.utils.translation import ugettext as _
from django.views import generic
from django.views.generic.edit import FormView
from django_messages.forms import ComposeForm
# from django.http.response import HttpResponseForbidden
from travels.models import Travel
from travels.forms import TravelForm, TravelListForm
from travels.tasks import inform_requesters_task


class TravelList(generic.ListView, FormView):
    """
    List view of all available travels
    """
    template_name = 'travel_list.html'
    queryset = Travel.objects.all().order_by('-journey_start')
    form_class = TravelListForm


class TravelDetail(generic.DetailView):
    """
    Detail view for a single post and an apply form
    TODO: Currently recipient and subject are just hidden, we need to modify
    forms to ignore changes coming from post and use details we want, i.e.
    someone can "unhide" recipient and subject and send whatever they want
    """
    queryset = Travel.objects.all()

    @property
    def travel_icon(self):
        """
        Return a travel icon depending on type of travel.
        Icons list:
        http://127.0.0.1:8000/static/unify/shortcode_icon_line_transport.html
        """
        icons = {
            'road': 'icon-transport-028',
            'sea': 'icon-transport-012',
            'air': 'icon-transport-026',
            'train': 'icon-transport-043',
            'walk': 'icon-travel-074',
            'interstellar': 'icon-transport-095',
        }
        travel_type = self.get_object().journey_type
        if travel_type in icons:
            return icons[travel_type]
        else:
            return 'icon-transport-042'

    def get_context_data(self, **kwargs):
        context = super(TravelDetail, self).get_context_data(**kwargs)
        travel = self.get_object()
        context['form'] = ComposeForm()
        context['subject'] = \
            _('Delivery request for {} - {} travel').format(
                travel.origin.name_ascii, travel.destination.name_ascii)
        context['message_placeholder'] = _('Please describe your package here.')
        return context


class TravelCreate(generic.CreateView):
    """
    Travel create view
    """
    model = Travel
    form_class = TravelForm

    def form_valid(self, form):
        form.instance.traveller = self.request.user
        return super(TravelCreate, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, _('Travel was successfully created'))
        inform_requesters_task.delay(self.object.id)
        return reverse('travel-detail',
                       args=(self.object.id, self.object.slug))


class TravelUpdate(generic.UpdateView):
    """
    Travel update view
    """
    model = Travel
    form_class = TravelForm

    def get_success_url(self):
        messages.success(self.request, _('Travel successfully updated'))
        inform_requesters_task.delay(self.object.id)
        return reverse('travel-detail',
                        args=(self.object.id, self.object.slug))

class TravelDelete(generic.DeleteView):
    """
    Travel delete view
    """
    model = Travel

    def get_success_url(self):
        messages.success(self.request, _('Travel successfully deleted'))
        return reverse_lazy('travels')

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user """
        travel = super(TravelDelete, self).get_object()
        if not travel.traveller == self.request.user:
            raise Http404
        return travel

travels/templates/travels/travel_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load tz %}
{% load i18n %}
{% block title %}
<title>{% trans 'Travel' %} | Post4Tips</title>
{% endblock %}
{% block head %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'assets/plugins/sky-forms-pro/skyforms/css/sky-forms.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/sky-forms-pro/skyforms/custom/custom-sky-forms.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker3.css' %}">
{% endblock %}
{% block content %}
<div class="container content">
    <header class="headline">
      <h2>{% trans 'Travel Details' %}</h2>
    </header>
  <div class="row">
    <section class="col-md-5 col-xs-12 bq-green">
        <h4><em>{% trans 'From' %}</em></h4>
        <p class="lead">{{ travel.origin.get_display_name }}</p>
    </section>
    <section class="col-md-2 col-xs-12 service-block">
      <i class="icon-custom icon-custom-detail icon-color-u icon-lg rounded-x icon-line {{ view.travel_icon }}" data-toggle="tooltip" data-original-title="{{ travel.get_journey_type_display }}"></i>
    </section>
    <section class="col-md-5 col-xs-12 text-right bq-green">
        <h4><em>{% trans 'To' %}</em></h4>
        <p class="lead">{{ travel.destination.get_display_name }}</p>
    </section>
  </div>
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <dl class="col-md-6 content-boxes-v3">
        <div class="clearfix margin-bottom-15">
          <a href="{% url 'account-guest-view' travel.traveller.id %}"><i class="icon-custom icon-custom-detail icon-color-u icon-lg rounded-x icon-line icon-travel-074" data-toggle="tooltip" data-original-title="View user account"></i></a>
          <div class="content-boxes-in-v3">
            <h5 class="content-h5-margin"><em><strong>{% trans 'Traveller' %}</strong></em></h5>
            <h4>{% if travel.traveller.first_name or travel.traveller.last_name %}
                  {{ travel.traveller.get_full_name }}
                {% else %}
                  {{ travel.traveller.username }}
                {% endif %}
            </h4>
          </div>
        </div>
      </dl>
      <dl class="col-md-6 content-boxes-v3">
        <div class="clearfix margin-bottom-15">
          <i class="icon-custom icon-custom-detail icon-color-u icon-lg rounded-x icon-line icon-communication-146"></i>
          <div class="content-boxes-in-v3">
            <h5 class="content-h5-margin"><em><strong>{% trans 'Travel start date' %}</strong></em></h5>
            <h4>{{ travel.journey_start|date:"d E Y" }}</h4>
          </div>
        </div>
      </dl>
      <div class="headline">
        <h4>{% trans 'Additional details' %}</h4>
      </div>
      <dl>
        {% if travel.journey_start != travel.journey_end %}
        <dt>{% trans 'Travel End Date' %}</dt>
        <dd>{{ travel.journey_end|date:"d E Y" }}</dd>
        {% endif %}
        <dt>{% trans 'Max Weight' %}</dt>
        <dd>{{ travel.get_max_weight_display }}</dd>
        <dt>{% trans 'Max Size' %}</dt>
        <dd>{{ travel.get_max_size_display }}</dd>
        <dt>{% trans 'Can Carry For Free' %}</dt>
        <dd>{% if travel.free %}{% trans 'Yes' %}{% else %}{% trans 'No' %}{% endif %}</dd>
      </dl>
    </div>
    <div class="col-md-6 col-xs-12">
      <input type="hidden" id="origin-latitude" name="variable" value="{{ travel.origin.latitude }}" readonly>
      <input type="hidden" id="origin-longitude" name="variable" value="{{ travel.origin.longitude }}" readonly>
      <input type="hidden" id="destination-latitude" name="variable" value="{{ travel.destination.latitude }}" readonly>
      <input type="hidden" id="destination-longitude" name="variable" value="{{ travel.destination.longitude }}" readonly>
      <div id="map" class="map margin-bottom-50"></div>
    </div>
  </div>
  {% if user == travel.traveller %}
    <form action="{% url 'travel-delete' travel.id travel.slug %}" method="post" class="form-horizontal">
      {% csrf_token %}
      <button type="button" class="btn-u btn-u-default" onclick="window.history.back();">{% trans 'Back' %}</button>
      <a class="btn-u btn-u-default" href="{% url 'travel-edit' travel.id travel.slug %}">{% trans 'Edit' %}</a>
      <button onclick="return confirm('Are you sure you want to delete this travel?')" class="btn-u btn-u-red">{% trans 'Delete' %}</button>
    </form>
  {% else %}
  <a class="btn-u btn-u-default" href="javascript:history.back()">{% trans 'Back' %}</a>
   <!-- Bootstrap Modals With Forms -->
    <button class="btn-u" data-toggle="modal" data-target="#responsive">{% trans 'Apply' %}</button>
    <div class="modal fade" id="responsive" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="{% url 'messages:messages_compose' %}?next={% url 'travel-detail' travel.id %}" class="sky-form form-horizontal" method="post">
                {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel4">{{ subject }}</h4>
                </div>
                <div class="modal-body">
                    <input id="{{ form.recipient.id_for_label }}" name="{{ form.recipient.html_name }}" type="hidden" value="{{ travel.traveller.username }}">
                    <input id="{{ form.subject.id_for_label }}" name="{{ form.subject.html_name }}" type="hidden" value="{{ subject }}">
                    <div class="row">
                        <div class="col-md-12 col-xs-10">
                            <label class="textarea textarea-resizable {% if form.body.errors %} state-error{% endif %}">
                                <textarea style="height: 150px;" id="{{ form.body.id_for_label }}" name="{{ form.body.html_name }}" placeholder="{{ message_placeholder }}" autofocus></textarea>
                            </label>
                            {% if form.body.help_text %}
                            <span id="help_{{ form.body.html_name }}" class="help-block">{{ form.body.help_text }}</span>
                            {% endif %}
                            {% if form.body.errors %}
                            {% for error in form.body.errors %}
                            <div class="alert alert-danger" role="alert">
                              <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                              <span class="sr-only">Error:</span>
                                {{ error|escape }}
                            </div>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn-u btn-u-default" data-dismiss="modal">{% trans 'Close' %}</button>
                    <button type="submit" id="submit" class="btn-u btn-u-primary odom-submit">{% trans 'Send' %}</button>
                </div>
                </form>
            </div>
        </div>
    </div>
<!-- End Bootstrap Modals With Forms -->
  {% endif %}
</div>
{% endblock %}
{% block foot %}
{{ block.super }}
<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyAia8-jJOAo2XJL7Tk3QedcbpV11OWR9Ls"></script>
<script type="text/javascript" src="{% static 'assets/plugins/gmap/gmap.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/maps.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/custom.js' %}"></script>
{% endblock %}